### PR TITLE
Improve Travis-CI and some small packaging improvements

### PR DESCRIPTION
**Pull request by ocefpaf**
@jhamman I left all the commits here to help the review, we can always squash it later.

If this is OK with you I'll start working on AppVeyor next.

### CODE REVIEW

**Comment by jhamman** [comment]
This looks fine to me. Do you want to do the Appveyor changes in this PR?

**Comment by ocefpaf** [comment]
> Do you want to do the Appveyor changes in this PR

I probably won't have time this week to do so. So maybe it is better to merge this first and I'll send another PR later.

**Comment by jhamman** [comment]
Thanks @ocefpaf

**Comment by ocefpaf** [comment]
Thank you for taking the time to split `netcdftime` from `netCDF4-python`!

**Pull request merged**
